export let cultureElements = [
	{
		id: '1',
		isHidden: true,
		site: null,
		title: 'Аварский этноспорт',
		region: 'Дагестан, республика',
		level: 'субэтнос',
		assemblyDate: '2024-02-14T00:00:00+03:00',
		logo: null,
		gallery: [],
		textBlock1: null,
		textBlock2: null,
		isEventsByDiscipline: false,
		isParticipantsByDiscipline: true,
		isParticipantsByEvents: false,
	},
	{
		id: '2',
		isHidden: false,
		site: 'http://ethnosport.ru',
		title: 'Русский этноспорт',
		region: 'Россия',
		level: 'регион',
		assemblyDate: '2024-02-02T00:00:00+03:00',
		logo: null,
		gallery: [],
		textBlock1: null,
		textBlock2: null,
		isEventsByDiscipline: true,
		isParticipantsByDiscipline: false,
		isParticipantsByEvents: false,
	},
	{
		id: '3',
		isHidden: false,
		site: 'http://ethnosport-buryatia.ru',
		title: 'Бурятский этноспорт',
		region: 'Бурятия, республика',
		level: 'государство',
		assemblyDate: '2024-01-17T00:00:00+03:00',
		logo: null,
		gallery: [],
		textBlock1: null,
		textBlock2: null,
		isEventsByDiscipline: true,
		isParticipantsByDiscipline: false,
		isParticipantsByEvents: false,
	},
	{
		id: '4',
		isHidden: false,
		site: 'http://bigmanitoodwelling.com',
		title: 'Башкирский этноспорт',
		region: 'без привязки',
		level: 'этнос',
		assemblyDate: '2024-02-02T00:00:00+03:00',
		logo: null,
		gallery: [],
		textBlock1: null,
		textBlock2: null,
		isEventsByDiscipline: true,
		isParticipantsByDiscipline: false,
		isParticipantsByEvents: false,
	},
	{
		id: '5',
		isHidden: false,
		site: 'http://bigmanitoodwelling.com',
		title: 'Ханты-Мансийский этноспорт',
		region: 'без привязки',
		level: 'этнос',
		assemblyDate: '2024-02-02T00:00:00+03:00',
		logo: null,
		gallery: [],
		textBlock1: null,
		textBlock2: null,
		isEventsByDiscipline: true,
		isParticipantsByDiscipline: false,
		isParticipantsByEvents: false,
	},
	{
		id: '6',
		isHidden: false,
		site: 'http://югра-мегаспорт.рф',
		title: 'Этноспорт коренных народов Северной Америки',
		region: 'ХМАО-Югра',
		level: 'этнос',
		assemblyDate: '2024-12-25T00:00:00+03:00',
		logo: null,
		gallery: [],
		textBlock1: null,
		textBlock2: null,
		isEventsByDiscipline: true,
		isParticipantsByDiscipline: false,
		isParticipantsByEvents: false,
	},
	{
		id: '7',
		isHidden: true,
		site: null,
		title: 'Аварский этноспорт',
		region: 'Дагестан, республика',
		level: 'субэтнос',
		assemblyDate: '2024-02-14T00:00:00+03:00',
		logo: null,
		gallery: [],
		textBlock1: null,
		textBlock2: null,
		isEventsByDiscipline: false,
		isParticipantsByDiscipline: true,
		isParticipantsByEvents: false,
	},
]
